name: marpf
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=2.3.*
  - scipy=1.16.*
  - matplotlib=3.9.*
  - pillow=10.*        # needed if you save GIFs
  - ffmpeg>=6,<8       # needed if you save MP4s
  - pip
